[ShadowIllusion]
txtClassname=shadowillusionOfficialV3
txtPartialcap=Shadowillusion
txtBaseAddress=ShadowIllusion_dx.exe
txtadrLocalPlayer=&H000B680D0
txttibia_HealthOffSet=&H0418
txttibia_ManaOffSet=&H0450
txtLightOffset=&H0ad
txtredSquare=&H0B680D4
txtposx_base = &HB686B8
txtposy_base = &HB686B8
txtposz_base = &HB686B8

# Caminhos de Offsets (conforme suas imagens)
path_x = 18, 4, 10, 70, 4, 0, 3C0
path_y = 18, 4, 10, 70, 4, 0, 3C4
path_z = 18, 4, 10, 70, 4, 0, 3C8


#Coordenada,Base Address (Offset),Sequência de Offsets
#X (Leste/Oeste),ShadowIllusion_dx.exe + 00B686B8,"18, 4, 38, 70, 4, 0, C8"
#Y (Norte/Sul),ShadowIllusion_dx.exe + 002E8,"D8C, 658, 3D4, 268, B00"
#Z (Andar),ShadowIllusion_dx.exe + 00B686B8,"18, 4, 10, 70, 4, 0, 3C8"

[Imperianic]
txtClassname=imperianic
txtPartialcap=Imperianic
txtBaseAddress=Imperianic DirectX9.exe
txtadrLocalPlayer=&H01B8138
txttibia_HealthOffSet=&H0950
txttibia_ManaOffSet=&H0A10
txtLightOffset=&H120
txtredSquare=&H1B813C

[Miracle74]
txtClassname=Miracle 7.4
txtPartialcap=Miracle 7.4
txtBaseAddress=dx.exe
txtadrLocalPlayer=&H929840
txttibia_HealthOffSet=&H04A0
txttibia_ManaOffSet=&H04F0
txtLightOffset=&H0ad
txtredSquare=&H929844

[Realera]
txtClassname=RealeraOTCv8
txtPartialcap=RealeraOTCv8
txtBaseAddress=dx.exe
txtadrLocalPlayer=&H92CBC0
txttibia_HealthOffSet=&H0480
txttibia_ManaOffSet=&H04B8
txtredSquare=&H92CBC4




